version: "3"

services:
    # NGINX
    nginx:
        build:
            # 从根目录下的nginx文件夹下构建
            context: ./services/nginx
            args:
                TIMEZONE: ${TIMEZONE}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        # 容器名称
        container_name: "nginx"
        ports:
            - "80:80"
        links:
             - php7_4
        volumes:
            # 挂载nginx配置至容器
            - ./volumes/nginx/conf.d:/etc/nginx/conf.d:rw
            # 挂载web项目目录至容器
            - ~/data/webroot:/home/www:rw
        environment:
            TZ: "$TIMEZONE"
        restart: always
        networks:
            - default
            - dev-network
    # mysql57运行环境，也是网络名称
    mysql5_7:
        build:
            # 从根目录下的mysql57文件夹下构建
            context: ./services/mysql5.7
            args:
                TIMEZONE: ${TIMEZONE}
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        # 容器名称
        container_name: "mysql5_7"
        #image: mysql57:latest
        cap_add:
            - SYS_PTRACE
        # 端口映射（不需要暴露端口）
        ports:
            - "3306:3306"
        volumes:
            # 将mysql配置复制过去
            - ./volumes/mysql/5.7/my.cnf:/etc/my.cnf:rw
            # 将mysql数据库目录映射至容器
            - ~/data/db/mysql/5.7/data:/var/lib/mysql:rw
        restart: always
        # 网络
        networks:
            - default
            - dev-network
    # php5.6-fpm运行环境，也是网络名称
    php5_6:
        build:
            context: ./services/php5.6
            # 环境变量传入
            args:
                TIMEZONE: ${TIMEZONE}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
                COMPOSER_MIRRORS_URL: ${COMPOSER_MIRRORS_URL}
        # 容器名称
        container_name: "php5_6"
        # 容器的权限设置（privileged/cap-add/cap-drop）
        cap_add:
            - SYS_PTRACE
        # 端口映射（不需要暴露端口）
        ports:
            - "${PHP5_6_FPM_EXPOSED_PORT}:9000"
        extra_hosts:
            - "fairs.dev.com:${MAIN_HOST_IP}"
            - "fairs-server.dev.com:${MAIN_HOST_IP}"
        volumes:
            # 挂载web项目目录至容器
            - ~/data/webroot:/home/www:rw
        restart: always
        # 网络
        networks:
            - default
            - dev-network
    # php7.0-fpm运行环境，也是网络名称
    php7_0:
        build:
            context: ./services/php7.0
            # 环境变量传入
            args:
                TIMEZONE: ${TIMEZONE}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
                COMPOSER_MIRRORS_URL: ${COMPOSER_MIRRORS_URL}
        # 容器名称
        container_name: "php7_0"
        # 容器的权限设置（privileged/cap-add/cap-drop）
        cap_add:
            - SYS_PTRACE
        # 端口映射（不需要暴露端口）
        ports:
            - "${PHP7_0_FPM_EXPOSED_PORT}:9000"
        extra_hosts:
            - "fairs.dev.com:${MAIN_HOST_IP}"
            - "fairs-server.dev.com:${MAIN_HOST_IP}"
        volumes:
            # 挂载web项目目录至容器
            - ~/data/webroot:/home/www:rw
        restart: always
        # 网络
        networks:
            - default
            - dev-network
    # php7.1-fpm运行环境，也是网络名称
    php7_1:
        build:
            context: ./services/php7.1
            # 环境变量传入
            args:
                TIMEZONE: ${TIMEZONE}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
                COMPOSER_MIRRORS_URL: ${COMPOSER_MIRRORS_URL}
        # 容器名称
        container_name: "php7_1"
        # 容器的权限设置（privileged/cap-add/cap-drop）
        cap_add:
            - SYS_PTRACE
        # 端口映射（不需要暴露端口）
        ports:
            - "${PHP7_1_FPM_EXPOSED_PORT}:9000"
        extra_hosts:
            - "fairs.dev.com:${MAIN_HOST_IP}"
            - "fairs-server.dev.com:${MAIN_HOST_IP}"
        volumes:
            # 挂载web项目目录至容器
            - ~/data/webroot:/home/www:rw
        restart: always
        # 网络
        networks:
            - default
            - dev-network
    # php7.2-fpm运行环境，也是网络名称
    php7_2:
        build:
            context: ./services/php7.2
            # 环境变量传入
            args:
                TIMEZONE: ${TIMEZONE}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
                COMPOSER_MIRRORS_URL: ${COMPOSER_MIRRORS_URL}
        # 容器名称
        container_name: "php7_2"
        # 容器的权限设置（privileged/cap-add/cap-drop）
        cap_add:
            - SYS_PTRACE
        # 端口映射（不需要暴露端口）
        ports:
            - "${PHP7_2_FPM_EXPOSED_PORT}:9000"
        extra_hosts:
            - "customer-pc.dev.com:${MAIN_HOST_IP}"
            - "pc-server.dev.com:${MAIN_HOST_IP}"
        volumes:
            # 挂载web项目目录至容器
            - ~/data/webroot:/home/www:rw
        restart: always
        # 网络
        networks:
            - default
            - dev-network
    # php7.3-fpm运行环境，也是网络名称
    php7_3:
        build:
            context: ./services/php7.3
            # 环境变量传入
            args:
                TIMEZONE: ${TIMEZONE}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
                COMPOSER_MIRRORS_URL: ${COMPOSER_MIRRORS_URL}
        # 容器名称
        container_name: "php7_3"
        # 容器的权限设置（privileged/cap-add/cap-drop）
        cap_add:
            - SYS_PTRACE
        # 端口映射（不需要暴露端口）
        ports:
            - "${PHP7_3_FPM_EXPOSED_PORT}:9000"
        extra_hosts:
            - "customer-pc.dev.com:${MAIN_HOST_IP}"
            - "pc-server.dev.com:${MAIN_HOST_IP}"
        volumes:
            # 挂载web项目目录至容器
            - ~/data/webroot:/home/www:rw
        restart: always
        # 网络
        networks:
            - default
            - dev-network
    # php7.4-fpm运行环境，也是网络名称
    php7_4:
        build:
            context: ./services/php7.4
            # 环境变量传入
            args:
                TIMEZONE: ${TIMEZONE}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
                COMPOSER_MIRRORS_URL: ${COMPOSER_MIRRORS_URL}
        # 容器名称
        container_name: "php7_4"
        # 容器的权限设置（privileged/cap-add/cap-drop）
        cap_add:
            - SYS_PTRACE
        # 端口映射（不需要暴露端口）
        ports:
            - "${PHP7_4_FPM_EXPOSED_PORT}:9000"
        extra_hosts:
            - "customer-pc.dev.com:${MAIN_HOST_IP}"
            - "pc-server.dev.com:${MAIN_HOST_IP}"
        volumes:
            # 挂载web项目目录至容器
            - ~/data/webroot:/home/www:rw
        restart: always
        # 网络
        networks:
            - default
            - dev-network
    # es6_8_12运行环境，也是网络名称
    es6_8:
        build:
            # 从根目录下的elasticsearch-6.8.12文件夹下构建
            context: ./services/elasticsearch-6.8.12
            args:
                TIMEZONE: ${TIMEZONE}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        # 容器名称
        container_name: "es68"
        cap_add:
            - SYS_PTRACE
        # 端口映射（不需要暴露端口）
        ports:
            - "9200:9200"
        volumes:
            # 挂载es配置至容器
            - ./volumes/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
            # 挂载es数据库目录至容器
            - ~/data/db/es/6.8.12/data:/usr/share/elasticsearch/data:rw
            # 挂载es日志目录至容器
            - ~/data/db/es/6.8.12/logs:/usr/share/elasticsearch/logs:rw
        restart: always
        # 网络
        networks:
            - default
            - dev-network
    # redis运行环境，也是网络名称
    redis:
        build:
            # 从根目录下的redis文件夹下构建
            context: ./services/redis
            args:
                TIMEZONE: ${TIMEZONE}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        # 容器名称
        container_name: "redis"
        cap_add:
            - SYS_PTRACE
        # 端口映射（不需要暴露端口）
        ports:
            - "6379:6379"
        volumes:
            # 挂载redis配置至容器
            - ./volumes/redis/conf/redis.conf:/etc/redis.conf:rw
            # 挂载redis数据库目录至容器
            - ~/data/db/redis/6.2.4/data:/data:rw
            # 挂载redis日志目录至容器
            - ~/data/db/redis/6.2.4/logs:/logs:rw
        # 覆盖容器启动的redis.conf
        command: redis-server /etc/redis.conf
        restart: always
        # 网络
        networks:
            - default
            - dev-network
networks:
    #default:
    dev-network:
        #external: true
        driver: bridge
        ipam:
            config:
                # 子网络
                - subnet: 10.8.0.0/16
